### ISSUE TITLE
Describir la metodología

### ISSUE THREAD

**Issue by JJ** [Slowmybrosh/TFG-DietPlanner#15]
Un capítulo que es prácticamente independiente es la descripción de la metodología, usando desarrollo ágil, GitHub y todo eso. Conviene que lo comiences lo antes posible, ya que se está usando desde el principio.

**Comment by Slowmybrosh** [comment]
Tengo escrita una especie de descripción de la metodología, a la espera de subirla. Pero tendría que cambiar un par de cosas antes de añadirla.
