### ISSUE TITLE
[HU01] - Estudiante - Encontrar recetas

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#22]
Como estudiante quiero ser capaz de encontrar recetas con los ingredientes que tengo en la despensa para obtener una alimentación que aproveche todos los recursos a mi alcance.

**Comment by JJ** [comment]
Tampoco es una historia de usuario. Las historias de usuario están siempre descritas en el dominio del problema y tienen que incluir alguna referencia al problema a resolver.
Están relacionadas con los user journeys de los que hablamos; ponlos aquí también.

**Comment by JJ** [comment]
El título de una historia de usuario debe reflejar de qué usuario se trata, no lo que tú vas a hacer. Por supuesto, para tener un usuario bien caracterizado necesitas usar la metodología de "personas", de la que hemos hablado repetidamente.

**Comment by Slowmybrosh** [comment]
Como se ha completado el análisis del despliegue para el usuario, se cierra razonadamente este issue
