### ISSUE TITLE
Un proyecto tiene que incluir claramente

### ISSUE THREAD

**Issue by JJ** [Slowmybrosh/TFG-DietPlanner#36]
1. Los problemas que tiene que resolver
2. Para quién va a resolverlo
3. Describir claramente quienes son los clientes
4. Tener historias de usuario que describa, para cada cliente, qué problemas esperan que el proyecto le solucione
5. Incluir un milestone que tenga como PMV todo esto descrito en la memoria *y* en este sitio.

Ahora mismo no tienes tal milestone, y las historias de usuario #1 y #22 son incorrectas, no corresponde a lo que hablamos en la tutoría, y no están reflejadas en la memoria. Tendrás que reformular todo esto en un milestone que vaya a continuación del que ya está completado.

**Comment by JJ** [comment]
@JJ Empieza por el 1 aquí.

**Comment by Slowmybrosh** [comment]
1. Se quiere resolver el problema de aprovechar todos los ingredientes que se tienen por casa y se desconocen recetas que usen exclusivamente esos ingredientes.

2. La solución pretende resolver el problema a un usuario con unos recursos limitados, como por ejemplo un estudiante que cuenta con una asignación mensual para comida y no puede excederse. 

3. El software puede ir dirigido a un amplio espectro de usuarios. Ya que no se pone ninguna limitación a quien quiera usar la aplicación.
