### ISSUE TITLE
User journey - Estudiante

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#37]
Un estudiante cuenta con un presupuesto ajustado al mes y no puede permitirse el lujo de comprar en el supermercado todos los días. Dicho estudiante se siente frustrado por no ser capaz de controlar sus gastos y que ciertos ingredientes que no utiliza asiduamente se le caduquen en la despensa. Descubre la plataforma y entra en ella para mirar de que se trata. Una vez accedido a la plataforma, se encontrará con el buscador de recetas donde introducirá los ingredientes que quiere gastar.  Posteriormente, el estudiante podrá encontrar a su disposición diferentes recetas que realizar con los ingredientes introducidos. Una vez seleccionada la receta el usuario puede comprobar los detalles de la misma.

**Comment by JJ** [comment]
Por favor, etiqueta las HUs bien y de forma correlativa. Los detalles de implementación, una vez más, no tienes por qué incluirlos; si puedes resolver el problema sin descargarse nada, mejor.

**Comment by Slowmybrosh** [comment]
Pero para un usuario, según mi opinión como consumidor, es más sencillo utilizar una aplicación que tienes en la pantalla de inicio del móvil a tener que buscar una plataforma web en el navegador

**Comment by JJ** [comment]
Tienes que tener en cuenta la opinión del estudiante (eso es la fase de "empatizar" de design thinking), no la tuya.

**Comment by Slowmybrosh** [comment]
Sí, cambié el user journey para que fuera una plataforma web accesible desde ordenador y dispositivos móviles. Eliminando tanto la problemática de descargar la aplicación como tener que echar un rato introduciendo ingredientes. Está todo justificado en la implementación

**Comment by JJ** [comment]
En general, los user journey van a ir a la documentación directamente; de ellos se sacarán las historias de usuario que son las que vas a incluir aquí. No aporta nada tener un user journey aquí, porque no se avanza código ni se crear issues que resuelvan problemas del user journey.

**Comment by JJ** [comment]
> Sí, cambié el user journey para que fuera una plataforma web accesible desde ordenador y dispositivos móviles. Eliminando tanto la problemática de descargar la aplicación como tener que echar un rato introduciendo ingredientes. Está todo justificado en la implementación

Ni los user journey ni las historias de usuario dicen nada de la implementación. La implementación es resultado del desarrollo del proyecto. Y por supuesto no se puede justificar "en la implementación", y menos si con "implementación" te refieres a la documentación, no a la implementación en si.

**Comment by Slowmybrosh** [comment]
Como se ha completado el análisis del despliegue para el usuario, se cierra razonadamente este issue
