### ISSUE TITLE
User journey - Persona mayor

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#38]
Una persona mayor que no se encuentra en disposición de ir al supermercado cada vez que le faltan ingredientes y tiene una despensa limitada. De pronto escucha la existencia de la plataforma y se dispone a probarla. Una vez que la encuentra, con dificultad debido a sus achaques de la edad y a su dificultad para entender las nuevas tecnologías, entra en ella. La aplicación muestra directamente el buscador para mayor agilidad, escribirá los ingredientes que quiere usar en la receta. La aplicación en este momento le podrá empezar a sugerir recetas con dichos ingredientes que tiene en su despensa. Después de elegir una receta, puede comprobar los detalles de la misma con detenimiento.

**Comment by JJ** [comment]
Si no tiene que meter los ingredientes, mejor. Y si no tiene que descargarse el app, mejor todavía, ¿no crees?

**Comment by Slowmybrosh** [comment]
En caso de eliminar la gestión de ingredientes, cada vez que se vaya a pedir una receta habría que hacer una lista de elementos de los ingredientes que se tengan en la despensa. Teniendo una lista previa se podría buscar directamente la query del usuario y enseñar las recetas que se puedan realizar

**Comment by Slowmybrosh** [comment]
Como se ha completado el análisis del despliegue para el usuario, se cierra razonadamente este issue
