### ISSUE TITLE
Fuente de recetas

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#43]
Para ofrecer recetas al usuario (#22 y #41) es necesario disponer un sitio donde encontrarlas.

**Comment by JJ** [comment]
Un issue tiene que describir un problema; si no dices claramente cómo y qué se va a usar de una receta *en tu contexto* es imposible saber si has resuelto el problema correctamente o no.
También "hallar" una fuente de recetas es un problema diferente.

**Comment by Slowmybrosh** [comment]
Debido a que es necesario contar con un conjunto de recetas para servir al usuario (#22 y #41), es necesario contar con dicho conjunto de recetas en un formato adecuado, por ello se debe estudiar una fuente donde obtener recetas.

Se tomarán en consideración las siguientes fuentes:
- Conjunto de recetas formateado para introducirlo en una base de datos
- Una base de datos con las recetas, ya preformada
- Una API que permita obtener recetas filtrando por ingredientes
