### ISSUE TITLE
Tienes que describir mucho mejor cuál es el producto mínimamente viable que se espera del milestone 0

### ISSUE THREAD

**Issue by JJ** [Slowmybrosh/TFG-DietPlanner#46]
El comprobador ortográfico y gramatical se hacen para algo, y forman parte de un PMV que necesitas para seguir adelante. Lo que buscas es, para #8 pero también para mi, asegurarte que el fuente de la memoria que está almacenado es correcto y genera correctamente la memoria. 
Por la parte de la  memoria, tienes que especificar claramente qué es lo que tiene que contener la memoria cuando se termine. Así que, por favor, escribe correctamente el milestone de esta forma y crea los issues correspondientes para terminar lo que no se ha hecho todavía.

**Comment by Slowmybrosh** [comment]
¿Qué milestone?

**Comment by Slowmybrosh** [comment]
Se han descrito los requisitos que debe tener el milestone para constituir el PMV. Se consideran los siguientes: 

1. Corrector ortográfico y gramatical
2. Automatizada la creación del fichero pdf con la memoria del proyecto haciendo uso de un gestor de tareas
3. Necesaria la aprobación del tutor
4. Especificar los capítulos iniciales que debe tener la memoria

**Comment by JJ** [comment]
Cuando hagas un PR del tema de implemtación describiéndolo, se puede cerrar.
