### ISSUE TITLE
Generar pdf del proyecto

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#47]
Es necesario contar con una herramienta que genere el pdf y lo suba al repositorio cuando se haga un merge en la rama principal. Manteniendo una documentación actualizada.

**Comment by JJ** [comment]
Todos los issues tienen que apuntar a una HU

**Comment by Slowmybrosh** [comment]
Para que #8 pueda leer el proyecto de manera sencilla, se debe generar el proyecto utilizando el gestor de tareas seleccionado para el proyecto.

**Comment by Slowmybrosh** [comment]
Al añadirse un gestor de tareas al proyecto, se añade también un comando para generar la memoria en formato pdf
