### ISSUE TITLE
Algunos tribunales necesitan una demo para "creerse" que el proyecto está hecho

### ISSUE THREAD

**Issue by JJ** [Slowmybrosh/TFG-DietPlanner#53]
A pesar de que los tests (unitarios y de otro tipo)  en desarrollo ágil son suficientes, algunos tribunales #8  necesitan y piden una demo. El último milestone debe incluirla.

**Comment by Slowmybrosh** [comment]
Como la demostración (prototipo) está concluida al alcanzar #93, se cierra este issue
