### ISSUE TITLE
Corregir explicación de la metodología en la introducción

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#58]
Primero o a la vez hay que entender qué problema tienen los usuarios.
https://github.com/Slowmybrosh/TFG-DietPlanner/pull/50#discussion_r1324425050_

No has explicado qué es un milestone y qué implica, ni qué tipo de desarrollo incluye el uso de milestones.
https://github.com/Slowmybrosh/TFG-DietPlanner/pull/50#discussion_r1324425717

**Comment by JJ** [comment]
Recuerda que los issues tienen siempre que formular un problema. Si dices "corregir" no especificas qué es lo que hay que corregir.
