### ISSUE TITLE
Evitar preguntas indeseadas del tribunal

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#70]
#8 no necesita saber las cosas que NO se han hecho en el proyecto, ya que puede dar lugar a preguntas indeseadas durante la fase de la defensa del proyecto. 

https://github.com/Slowmybrosh/TFG-DietPlanner/pull/68#discussion_r1333451593

**Comment by JJ** [comment]
Este también deberías dejarlo abierto hasta el final.
