### ISSUE TITLE
Buscador de recetas

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#87]
Para que #22 y #41 puedan encontrar recetas, es necesario crear un buscador de recetas que permita encontrar aquellas recetas que contengan exclusivamente los ingredientes proporcionados por el usuario. Además, para este buscador, es necesario desacoplar la conexión con la base de datos y la configuración de la misma.

**Comment by JJ** [comment]
NO hay ningún problema planteado, pero sí planteas una solución, en contra de las mejores prácticas.
