### ISSUE TITLE
Test Buscador

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#88]
Para asegurar que la funcionalidad para servir las recetas a los usuarios (#41 y #22) funciona (#85), es necesario contar con una serie de tests, permitiendo comprobar que los resultados son como se esperan antes de integrar nuevo código al proyecto. Para ello es necesario implementar una herramienta de testing y los test pertinentes para el buscador.

**Comment by JJ** [comment]
Los issues son problemas, no tareas, y para comprobar que los problemas se solucionan hay que hacer un test. Un test, por tanto, no puede ser *nunca* un issue.
