### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/TFG-DietPlanner#90]
Actualmente el usuario medio (#22 y #41) no puede acceder a la aplicación, para permitirle encontrar recetas de manera cómoda a un usuario sin conocimientos en programación, es necesario implementar un framework web para Python que permita gestionar la lógica de negocio y ofrecerla al usuario

**Comment by JJ** [comment]
No plantea un problema, ni el contexto, ni lo que se necesita. Prácticamente se puede cerrar con cualquier elección que se haga.

**Comment by Slowmybrosh** [comment]
Se ha cambiado la descripción del problema para reflejar el problema que se está abordando al implementar el framework
